output_dir = "foo"
max_failures = 10

[tests.basic]
command = "cat {file}" # filename replaced by input file
return_code = 0

[tests.lexer]
command = "cat {file}" # filename replaced by input file
return_code = 0
